name: vid2pdf
description: "Convert a video into a PDF series of stills."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  desktop_drop: ^0.6.0
  ffmpeg_cli: ^0.3.0
  file_picker: ^10.1.9
  flutter_dotenv: ^5.2.1
  mime: ^2.0.0
  path: ^1.9.1
  pdf: ^3.11.3
  window_manager: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
  assets:
    - .env

import_sorter:
  comments: false
